export const GET_PRODUCTS = "GET_PRODUCTS";
export const ADD_PRODUCT= "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const ADD_PRODUCT_TO_CART='ADD_PRODUCT_TO_CART'
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART'
export const UPDATE_PRODUCT_QUANTITY='UPDATE_PRODUCT_QUANTITY'
export const CLEAR_CART='CLEAR_CART'